#!/usr/bin/env node
/*
 * Static prerender for René’s Travel Agency.
 * ------------------------------------------------------------------
 * Same goal as Haul Yeah’s scripts/prerender.js (give crawlers real HTML on
 * every route), done without a headless browser: the app is rendered with
 * React’s server renderer from the SSR build, so it runs anywhere Node runs
 * (Cloudflare Pages build included) and nothing third-party ever loads.
 *
 * For every route in src/lib/routes.js it writes dist/<route>/index.html
 * with that page’s <title>, description, canonical, Open Graph tags and
 * JSON-LD, then generates:
 *   • dist/404.html          (Cloudflare Pages serves it for unknown URLs)
 *   • dist/sitemap.xml       (every indexable route, from the same table)
 *   • dist/_redirects        (301s from the 2016 .php URLs)
 * Exit code is non-zero if anything fails.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DIST = path.join(ROOT, "dist");
const SSR_DIR = path.join(ROOT, "dist-ssr");

const esc = (s = "") => String(s).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const jsonForScript = (obj) => JSON.stringify(obj).replace(/</g, "\\u003c");

function headTags(meta, siteConfig) {
  const name = siteConfig.business.shortName;
  const og = siteConfig.images.ogImage.src ? `${siteConfig.business.baseUrl}${siteConfig.images.ogImage.src}` : "";
  const tags = [
    `<title>${esc(meta.title)}</title>`,
    `<meta name="description" content="${esc(meta.description)}" />`,
    meta.robots ? `<meta name="robots" content="${esc(meta.robots)}" />` : "",
    meta.canonical ? `<link rel="canonical" href="${esc(meta.canonical)}" />` : "",
    `<meta property="og:site_name" content="${esc(name)}" />`,
    `<meta property="og:type" content="${esc(meta.ogType || "website")}" />`,
    `<meta property="og:title" content="${esc(meta.title)}" />`,
    `<meta property="og:description" content="${esc(meta.description)}" />`,
    meta.canonical ? `<meta property="og:url" content="${esc(meta.canonical)}" />` : "",
    og ? `<meta property="og:image" content="${esc(og)}" />` : "",
    `<meta name="twitter:card" content="${og ? "summary_large_image" : "summary"}" />`,
    ...(meta.jsonLd || []).map((obj) => `<script type="application/ld+json">${jsonForScript(obj)}</script>`),
  ];
  return tags.filter(Boolean).join("\n    ");
}

function writeRoute(file, html) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, html);
}

async function main() {
  const template = fs.readFileSync(path.join(DIST, "index.html"), "utf8");
  if (!template.includes("<!--app-html-->") || !template.includes("<!--app-head-->")) {
    throw new Error("dist/index.html is missing the <!--app-head--> or <!--app-html--> markers");
  }
  const entry = fs.readdirSync(SSR_DIR).find((f) => /^entry-server\.(m?js)$/.test(f));
  const ssr = await import(pathToFileURL(path.join(SSR_DIR, entry)).href);
  const { render, buildRoutes, notFoundMeta, legacyRedirects, siteConfig } = ssr;

  const routes = buildRoutes();
  const page = (meta, appHtml) =>
    template.replace("<!--app-head-->", headTags(meta, siteConfig)).replace("<!--app-html-->", appHtml);

  let count = 0;
  for (const meta of routes) {
    const html = page(meta, render(meta.path));
    const out = meta.path === "/" ? path.join(DIST, "index.html") : path.join(DIST, meta.path, "index.html");
    writeRoute(out, html);
    count += 1;
  }
  writeRoute(path.join(DIST, "404.html"), page(notFoundMeta, render("/__not-found__/")));

  // sitemap.xml: generated from the same route table, so new trips/partners appear automatically.
  const today = new Date().toISOString().slice(0, 10);
  const urls = routes
    .filter((r) => r.sitemap && r.canonical)
    .map((r) => `  <url><loc>${r.canonical}</loc><lastmod>${today}</lastmod><changefreq>${r.sitemap.changefreq}</changefreq><priority>${r.sitemap.priority}</priority></url>`);
  fs.writeFileSync(
    path.join(DIST, "sitemap.xml"),
    `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by scripts/prerender.mjs from src/lib/routes.js. Do not edit by hand. -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join("\n")}\n</urlset>\n`,
  );

  // _redirects: hand-written rules in public/_redirects (already copied to dist) + the legacy .php map.
  const redirectsPath = path.join(DIST, "_redirects");
  const manual = fs.existsSync(redirectsPath) ? fs.readFileSync(redirectsPath, "utf8").trimEnd() + "\n\n" : "";
  const legacy = legacyRedirects().map(([from, to]) => `${from}  ${to}  301`).join("\n");
  fs.writeFileSync(redirectsPath, `${manual}# Generated: old 2016 page URLs → new pages (from src/lib/routes.js)\n${legacy}\n`);

  fs.rmSync(SSR_DIR, { recursive: true, force: true });
  console.log(`prerendered ${count} routes + 404.html, sitemap.xml (${urls.length} urls), _redirects (${legacyRedirects().length} rules)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
